-- ================================================================================
--   innodb SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   innodb
--   Generated at:      Mon Jun 22 23:09:13 2009
--   Input Files:       estresadito.dia
-- 
-- ================================================================================

set autocommit = 0 ;

-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Mon Jun 22 23:09:12 2009
--     Input Files:       estresadito.dia

-- alter table alumnos drop constraint alumnos_fk_Generos_id-- (is implicitly done)
-- alter table alumnos drop constraint alumnos_fk_Estados_civiles_id-- (is implicitly done)
-- alter table alumnos drop constraint alumnos_fk_Nacionalidades_id-- (is implicitly done)
-- alter table alumnos drop constraint alumnos_fk_Municipios_estados_id-- (is implicitly done)
-- alter table alumnos_grupos drop constraint alumnos_grupos_fk_Alumnos_id-- (is implicitly done)
-- alter table alumnos drop constraint alumnos_fk_Status_id-- (is implicitly done)
-- alter table ciclos_escolares drop constraint ciclos_escolares_fk_Niveles_escolares_id-- (is implicitly done)
-- alter table maestros_materias drop constraint maestros_materias_fk_Materias_id-- (is implicitly done)
-- alter table maestros_materias drop constraint maestros_materias_fk_Maestros_id-- (is implicitly done)
-- alter table maestros_materias drop constraint maestros_materias_fk_Ciclos_escolares_id-- (is implicitly done)
-- alter table grupos drop constraint grupos_fk_Ciclos_escolares_id-- (is implicitly done)
-- alter table alumnos_grupos drop constraint alumnos_grupos_fk_Grupos_id-- (is implicitly done)
-- alter table calificaciones drop constraint calificaciones_fk_Alumnos_grupos_id-- (is implicitly done)
-- alter table calificaciones drop constraint calificaciones_fk_Maestros_materias_id-- (is implicitly done)
-- alter table pagos drop constraint pagos_fk_Alumnos_id-- (is implicitly done)
-- alter table pagos drop constraint pagos_fk_Costos_id-- (is implicitly done)
-- alter table costos drop constraint costos_fk_Niveles_escolares_id-- (is implicitly done)
-- alter table alumnos drop constraint alumnos_fk_Niveles_escolares_id-- (is implicitly done)


-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Mon Jun 22 23:09:12 2009
--     Input Files:       estresadito.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Mon Jun 22 23:09:12 2009
--     Input Files:       estresadito.dia



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Mon Jun 22 23:09:12 2009
--     Input Files:       estresadito.dia

 drop table if exists maestros ;
 drop table if exists alumnos ;
 drop table if exists generos ;
 drop table if exists pagos ;
 drop table if exists costos ;
 drop table if exists niveles_escolares ;
 drop table if exists estados_civiles ;
 drop table if exists nacionalidades ;
 drop table if exists municipios_estados ;
 drop table if exists grupos ;
 drop table if exists status ;
 drop table if exists materias ;
 drop table if exists ciclos_escolares ;
 drop table if exists maestros_materias ;
 drop table if exists calificaciones ;
 drop table if exists alumnos_grupos ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Mon Jun 22 23:09:12 2009
--     Input Files:       estresadito.dia


-- maestros
create table maestros (
  id                        int auto_increment not null,
  nombre                    varchar(50),
  apellido_paterno          varchar(50),
  apellido_materno          varchar(50),
  constraint pk_Maestros primary key (id)
) type = InnoDB ;

-- alumnos
create table alumnos (
  id                        int auto_increment not null,
  niveles_escolares_id      int not null,
  generos_id                int,
  estados_civiles_id        int,
  nacionalidades_id         int,
  municipios_estados_id     int,
  status_id                 int not null,
  clave                     varchar(50),
  nombre                    varchar(20),
  apellido_materno          varchar(20),
  apellido_paterno          varchar(20),
  nacimiento_fecha          date,
  nacimiento_lugar          varchar(50),
  nacimiento_estado         int,	-- toma los datos de la tabla municipios_estados
  curp                      varchar(50),
  domicilio_particular      varchar(100),
  entre_calles              varchar(100),
  codigo_postal             int(10),
  constraint pk_Alumnos primary key (id)
) type = InnoDB ;

-- generos
create table generos (
  id                        int auto_increment not null,
  valor                     varchar(10),
  constraint pk_Generos primary key (id)
) type = InnoDB ;

-- pagos
create table pagos (
  id                        int not null,
  alumnos_id                int not null,
  costos_id                 int not null,
  cobertura_inicial         date,
  cobertura_final           date,
  cobertura_total           date,
  importe                   float,
  adeudo                    float,
  observaciones             text,
  fecha                     timestamp default NOW(),
  constraint pk_Pagos primary key (id)
) type = InnoDB ;

-- costos
create table costos (
  id                        int auto_increment not null,
  niveles_escolares_id      int not null,
  concepto                  varchar(50),
  importe                   float,
  descuento                 int(1),
  descuento_porcentaje      int(1),
  constraint pk_Costos primary key (id)
) type = InnoDB ;

-- niveles_escolares
create table niveles_escolares (
  id                        int auto_increment not null,
  valor                     varchar(20),
  constraint pk_Niveles_escolares primary key (id)
) type = InnoDB ;

-- estados_civiles
create table estados_civiles (
  id                        int auto_increment not null,
  valor                     varchar(20),
  constraint pk_Estados_civiles primary key (id)
) type = InnoDB ;

-- nacionalidades
create table nacionalidades (
  id                        int auto_increment not null,
  valor                     varchar(50),
  constraint pk_Nacionalidades primary key (id)
) type = InnoDB ;

-- municipios_estados
create table municipios_estados (
  id                        int auto_increment not null,
  municipio                 varchar(50),
  estado                    varchar(50),
  codigo_postal             int(10),
  constraint pk_Municipios_estados primary key (id)
) type = InnoDB ;

-- grupos
create table grupos (
  id                        int auto_increment not null,
  ciclos_escolares_id       int not null,
  grado                     int(1) not null,
  grupo                     varchar(1) not null,
  constraint pk_Grupos primary key (id)
) type = InnoDB ;

-- status
create table status (
  id                        int auto_increment not null,
  valor                     varchar(20),
  constraint pk_Status primary key (id)
) type = InnoDB ;

-- materias
create table materias (
  id                        int auto_increment not null,
  nombre                    varchar(50),
  constraint pk_Materias primary key (id)
) type = InnoDB ;

-- ciclos_escolares
create table ciclos_escolares (
  id                        int auto_increment not null,
  niveles_escolares_id      int not null,
  inicio                    int(5),
  fin                       int(5),
  constraint pk_Ciclos_escolares primary key (id)
) type = InnoDB ;

-- maestros_materias
create table maestros_materias (
  id                        int auto_increment not null,
  maestros_id               int not null,
  materias_id               int not null,
  ciclos_escolares_id       int not null,
  grado                     int(1),
  constraint pk_Maestros_materias primary key (id)
) type = InnoDB ;

-- calificaciones
create table calificaciones (
  id                        int auto_increment not null,
  alumnos_grupos_id         int not null,
  maestros_materias_id      int not null,
  constraint pk_Calificaciones primary key (id)
) type = InnoDB ;

-- alumnos_grupos
create table alumnos_grupos (
  id                        int auto_increment not null,
  grupos_id                 int not null,
  alumnos_id                int not null,
  constraint pk_Alumnos_grupos primary key (id)
) type = InnoDB ;


















-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Mon Jun 22 23:09:12 2009
--     Input Files:       estresadito.dia




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Mon Jun 22 23:09:12 2009
--     Input Files:       estresadito.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Mon Jun 22 23:09:12 2009
--     Input Files:       estresadito.dia


-- inserts for generos (id, valor)
insert into generos (id, valor) values ( 1, 'Masculino' ) ;
insert into generos (id, valor) values ( 2, 'Femenino' ) ;

-- inserts for estados_civiles (id, valor)
insert into estados_civiles (id, valor) values ( 1, 'Soltero' ) ;
insert into estados_civiles (id, valor) values ( 2, 'Unión libre' ) ;
insert into estados_civiles (id, valor) values ( 3, 'Casado' ) ;
insert into estados_civiles (id, valor) values ( 4, 'Divorciado' ) ;
insert into estados_civiles (id, valor) values ( 5, 'Viudo' ) ;

-- inserts for status (id, valor)
insert into status (id, valor) values ( 1, 'Ok' ) ;
insert into status (id, valor) values ( 2, 'Baja' ) ;
insert into status (id, valor) values ( 3, 'Suspendido' ) ;
insert into status (id, valor) values ( 4, 'Expulsado' ) ;

-- inserts for niveles_escolares (id, valor)
insert into niveles_escolares (id, valor) values ( 1, 'Primaria' ) ;
insert into niveles_escolares (id, valor) values ( 2, 'Secundaria' ) ;
insert into niveles_escolares (id, valor) values ( 3, 'Preparatoria' ) ;


-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   innodb
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Mon Jun 22 23:09:12 2009
--     Input Files:       estresadito.dia

alter table alumnos add constraint alumnos_fk_Generos_id
  foreign key (generos_id)
  references generos (id)  ;
alter table alumnos add constraint alumnos_fk_Estados_civiles_id
  foreign key (estados_civiles_id)
  references estados_civiles (id)  ;
alter table alumnos add constraint alumnos_fk_Nacionalidades_id
  foreign key (nacionalidades_id)
  references nacionalidades (id)  ;
alter table alumnos add constraint alumnos_fk_Municipios_estados_id
  foreign key (municipios_estados_id)
  references municipios_estados (id)  ;
alter table alumnos_grupos add constraint alumnos_grupos_fk_Alumnos_id
  foreign key (alumnos_id)
  references alumnos (id)  ;
alter table alumnos add constraint alumnos_fk_Status_id
  foreign key (status_id)
  references status (id)  ;
alter table ciclos_escolares add constraint ciclos_escolares_fk_Niveles_escolares_id
  foreign key (niveles_escolares_id)
  references niveles_escolares (id)  ;
alter table maestros_materias add constraint maestros_materias_fk_Materias_id
  foreign key (materias_id)
  references materias (id)  ;
alter table maestros_materias add constraint maestros_materias_fk_Maestros_id
  foreign key (maestros_id)
  references maestros (id)  ;
alter table maestros_materias add constraint maestros_materias_fk_Ciclos_escolares_id
  foreign key (ciclos_escolares_id)
  references ciclos_escolares (id)  ;
alter table grupos add constraint grupos_fk_Ciclos_escolares_id
  foreign key (ciclos_escolares_id)
  references ciclos_escolares (id)  ;
alter table alumnos_grupos add constraint alumnos_grupos_fk_Grupos_id
  foreign key (grupos_id)
  references grupos (id)  ;
alter table calificaciones add constraint calificaciones_fk_Alumnos_grupos_id
  foreign key (alumnos_grupos_id)
  references alumnos_grupos (id)  ;
alter table calificaciones add constraint calificaciones_fk_Maestros_materias_id
  foreign key (maestros_materias_id)
  references maestros_materias (id)  ;
alter table pagos add constraint pagos_fk_Alumnos_id
  foreign key (alumnos_id)
  references alumnos (id)  ;
alter table pagos add constraint pagos_fk_Costos_id
  foreign key (costos_id)
  references costos (id)  ;
alter table costos add constraint costos_fk_Niveles_escolares_id
  foreign key (niveles_escolares_id)
  references niveles_escolares (id)  ;
alter table alumnos add constraint alumnos_fk_Niveles_escolares_id
  foreign key (niveles_escolares_id)
  references niveles_escolares (id)  ;

-- innodb requires a special 'quit' command
commit ;

